server:
  port: 8080

spring:
  mvc:
    static-path-pattern: static/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
    mode: HTML

  freemarker:
    suffix: .html
    request-context-attribute: request
    charset: utf-8
  aop:
    proxy-target-class: true


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiangzi.model


logging:
  config: classpath:logback-spring.xml
  level:
    com.xiangzi.dao: debug

